version: "3.7"
services:
  db2:
    image: ibmcom/db2
    privileged: true
    environment: 
      DBNAME: devdb
      LICENSE: accept
      DB2INSTANCE: db2inst1
      DB2INST1_PASSWORD: pwd4dev
    ports:
      - target: "50000"
        published: "50000" 